name: ArgoCD-Action - Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to execute'
        required: true
        default: 'plan'
        type: choice
        options:
          - 'plan'
          - 'apply'
          - 'destroy'

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9 

    - name: Terraform Init
      run: terraform init

    - name: Terraform ${{ github.event.inputs.action }}
      run: |
        terraform workspace select default || terraform workspace new default
        if [ "${{ github.event.inputs.action }}" == "plan" ]; then
          terraform plan
        elif [ "${{ github.event.inputs.action }}" == "apply" ]; then
          terraform apply -auto-approve
        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
          terraform destroy -auto-approve
        fi
